version: '3'

services:
  workspace_oikawa:
    image: workspace_oikawa
    build:
      context: ./
      dockerfile: docker/workspace/Dockerfile
    ports:
      - "8881:8881"
    volumes:
      - ./:/workspace
      - ../data/:/data
      - ../frame_data/:/frame_data
    working_dir: "/workspace"
    tty: true
  python:
    depends_on:
      - workspace_oikawa
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./:/workspace
      - ../data/:/data
      - ../frame_data/:/frame_data
    working_dir: "/workspace"
