version: '3'

services:
  activity_recognition_workspace_oikawa:
    image: activity_recognition_workspace_oikawa
    build:
      context: ./
      dockerfile: docker/workspace/Dockerfile
    ports:
      - "8881:8881"
    volumes:
      - ./:/workspace
    working_dir: "/workspace"
    tty: true
  activity_recognition_python_oikawa:
    depends_on:
      - activity_recognition_workspace_oikawa
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./:/workspace
    working_dir: "/workspace"
